from app.agents.models import AnalysisResult, Finding
from app.llm.client import OpenAIClient


class CriticAgent:
    def __init__(
        self,
        llm_client: OpenAIClient,
    ):
        self.llm_client = llm_client

    async def analyze(
        self,
        findings: list[Finding],
    ) -> AnalysisResult:

        if not findings:
            return AnalysisResult(findings=[])

        findings_context = []

        for index, finding in enumerate(
            findings,
            start=1,
        ):
            findings_context.append(
                f"""
Finding {index}:

Category: {finding.category}
Severity: {finding.severity}
Title: {finding.title}
File: {finding.file}
Line: {finding.line}

Description:
{finding.description}

Recommendation:
{finding.recommendation}
"""
            )

        context = "\n".join(findings_context)

        prompt = f"""
You are a senior software engineering reviewer
responsible for validating findings produced by
multiple specialized code-analysis agents.

The findings below were generated by:

- Security Agent
- Architecture Agent
- Testing Agent
- Dependency Agent
- Docker Agent

Your job is to review these findings and produce
a clean, deduplicated set of engineering findings.

IMPORTANT:

You are NOT discovering new issues.

Only review the findings provided below.

Your responsibilities:

1. Remove duplicate findings.
2. Merge findings that describe the same underlying issue.
3. Remove findings that are clearly unsupported or too vague.
4. Preserve concrete findings supported by the provided data.
5. Preserve the original category when possible.
6. Preserve the most appropriate severity.
7. Do not invent files, lines, vulnerabilities, or behavior.
8. Do not introduce new recommendations unrelated to
   the provided findings.
9. Prefer specific findings over generic findings.
10. If two findings describe the same issue from different
    perspectives, combine them into one clear finding.
11. Keep useful recommendations.
12. If no valid findings remain, return an empty findings array.

Severity must be one of:

critical
high
medium
low
info

Return ONLY the JSON object.

Do NOT use Markdown code fences.

Do NOT add explanations before or after the JSON.

The JSON must have exactly this structure:

{{
    "findings": [
        {{
            "category": "security",
            "severity": "high",
            "title": "Short issue title",
            "file": "path/to/file.py",
            "line": null,
            "description": "Explain the validated issue.",
            "recommendation": "Explain how it should be improved."
        }}
    ]
}}

Findings to review:

{context}
"""

        raw_response = await self.llm_client.analyze(
            prompt
        )

        cleaned_response = raw_response.strip()

        if cleaned_response.startswith("```json"):
            cleaned_response = cleaned_response[
                len("```json"):
            ].strip()

        elif cleaned_response.startswith("```"):
            cleaned_response = cleaned_response[
                len("```"):
            ].strip()

        if cleaned_response.endswith("```"):
            cleaned_response = cleaned_response[
                :-len("```")
            ].strip()

        return AnalysisResult.model_validate_json(
            cleaned_response
        )